---
title: "Phase 2"
output: html_document
---

```{r import dataset, echo=FALSE}
cohort <- dbGetQuery(sql,"select * from SAILW1224V.TS_ADMISSIONS")
patients <- dbGetQuery(sql, "select * from SAILW1224V.TS_PHASE2_ADMIS_SCORING")
nulls <- dbGetQuery(sql, "select * from SAILW1224V.TS_PHASE2_ICD10")
```

```{r correct columns and create new columns, echo = F}
cohort$SEX[cohort$SEX == 1] <- "Male"
cohort$SEX[cohort$SEX == 2] <- "Female"
cohort$SEX[is.na(cohort$SEX)] <- "Unknown"

cohort <- cohort %>% mutate(Age_Group = case_when(AGE <= 29 ~ '<30',
                                                  between(AGE, 30, 49) ~ '30-49',
                                                  between(AGE, 50, 69) ~ '50-69',
                                                  AGE >= 70 ~ '70 or older'))

cohort <- cohort %>% subset(!is.na(VARIABLE_LEVEL))
cohort$WIMD_2014_QUINTILE[cohort$START_DATE > '2020-03-01'] <- NA

patients$SEX[patients$SEX == 1] <- "Male"
patients$SEX[patients$SEX == 2] <- "Female"
patients$SEX[is.na(patients$SEX)] <- "Unknown"

patients <- patients %>% mutate(Age_Group = case_when(AGE <= 29 ~ '<30',
                                                      between(AGE, 30, 49) ~ '30-49',
                                                      between(AGE, 50, 69) ~ '50-69',
                                                      AGE >= 70 ~ '70 or older'))
patients$WIMD_2014_QUINTILE[patients$START_DATE > '2020-03-01'] <- NA

nulls$SEX[nulls$SEX == 1] <- "Male"
nulls$SEX[nulls$SEX == 2] <- "Female"
nulls$SEX[is.na(nulls$SEX)] <- "Unknown"

nulls <- nulls %>% mutate(Age_Group = case_when(AGE <= 29 ~ '<30',
                                                between(AGE, 30, 49) ~ '30-49',
                                                between(AGE, 50, 69) ~ '50-69',
                                                AGE >= 70 ~ '70 or older'))
nulls$WIMD_2014_QUINTILE[nulls$START_DATE > '2020-03-01'] <- NA
```

```{r overall counts, echo = F}
condition_admis <- cohort %>% group_by(VARIABLE_LEVEL) %>% summarise(Total = n())

sex_condition_admis <- cohort %>% group_by(SEX, VARIABLE_LEVEL) %>% summarise(Total = n())

age_condition_admis <- cohort %>% group_by(Age_Group, VARIABLE_LEVEL) %>% summarise(Total = n())

deprivation_condition_admis <- cohort %>% group_by(WIMD_2014_QUINTILE, VARIABLE_LEVEL) %>% summarise(Total = n())

shield_condition_admis <- pivot_longer(cohort, cols = c("TRANSPLANT", "CANCER", "RESPIRATORY", "ORGAN_DISEASE", "RARE_DISEASES", "IMMUNOSUPPRESSION_THERAPY",
                                                        "PREGNANCY", "RENAL_DIALYSIS", "OTHER", "GP_REFERRED", "NOT_KNOWN"),
                                       names_to = "Shield_Reason") %>% subset(value > 0) %>% group_by(Shield_Reason, VARIABLE_LEVEL) %>% summarise(Total = n())
```
```{r patient counts, echo = F}
patient_long_condition <- patients[, c(1, 17:46)] %>% pivot_longer(cols = c("RF", "CHF", "CARIT", "VALV", "PCD", "PVD", "HYPUNC", "HYPC", "PARA", "OND", "CPD", "DIABUNC",
                                                                            "DIABC", "HYPOTHY", "LD", "PUD", "LYMPH", "METACANC", "SOLIDTUM", "RHEUMD", "COAG", "OBES", "WLOSS",
                                                                            "FED", "BLANE", "DANE", "ALCOHOL", "DRUG", "PSYCHO", "DEPRE"),
                                                                   names_to = "VARIABLE_LEVEL") %>% subset(value > 0) %>% group_by(VARIABLE_LEVEL) %>% summarise(Total = n())

patient_long_cond_agg <- patients %>% group_by(NUM_CAT) %>% summarise(Total = n())

patient_long_cond_vw <- patients %>% group_by(VW_CAT) %>% summarise(Total = n())

patient_long_condition_sex <- patients[, c(1, 3, 17:46)] %>% pivot_longer(cols = c("RF", "CHF", "CARIT", "VALV", "PCD", "PVD", "HYPUNC", "HYPC", "PARA", "OND", "CPD", "DIABUNC",
                                                                                   "DIABC", "HYPOTHY", "LD", "PUD", "LYMPH", "METACANC", "SOLIDTUM", "RHEUMD", "COAG", "OBES", "WLOSS",
                                                                                   "FED", "BLANE", "DANE", "ALCOHOL", "DRUG", "PSYCHO", "DEPRE"),
                                                                          names_to = "VARIABLE_LEVEL") %>% subset(value > 0) %>% group_by(SEX, VARIABLE_LEVEL) %>% summarise(Total = n())

patient_long_cond_agg_sex <- patients %>% group_by(SEX, NUM_CAT) %>% summarise(Total = n())

patient_long_cond_vw_sex <- patients %>% group_by(SEX, VW_CAT) %>% summarise(Total = n())

patient_long_condition_age <- patients[, c(1, 17:46, 51)] %>% pivot_longer(cols = c("RF", "CHF", "CARIT", "VALV", "PCD", "PVD", "HYPUNC", "HYPC", "PARA", "OND", "CPD", "DIABUNC",
                                                                                   "DIABC", "HYPOTHY", "LD", "PUD", "LYMPH", "METACANC", "SOLIDTUM", "RHEUMD", "COAG", "OBES", "WLOSS",
                                                                                   "FED", "BLANE", "DANE", "ALCOHOL", "DRUG", "PSYCHO", "DEPRE"),
                                                                          names_to = "VARIABLE_LEVEL") %>% subset(value > 0) %>% group_by(Age_Group, VARIABLE_LEVEL) %>% summarise(Total = n())

patient_long_cond_agg_age <- patients %>% group_by(Age_Group, NUM_CAT) %>% summarise(Total = n())

patient_long_cond_vw_age <- patients %>% group_by(Age_Group, VW_CAT) %>% summarise(Total = n())

patient_long_condition_dep <- patients[, c(1, 5, 17:46)] %>% pivot_longer(cols = c("RF", "CHF", "CARIT", "VALV", "PCD", "PVD", "HYPUNC", "HYPC", "PARA", "OND", "CPD", "DIABUNC",
                                                                                   "DIABC", "HYPOTHY", "LD", "PUD", "LYMPH", "METACANC", "SOLIDTUM", "RHEUMD", "COAG", "OBES", "WLOSS",
                                                                                   "FED", "BLANE", "DANE", "ALCOHOL", "DRUG", "PSYCHO", "DEPRE"),
                                                                          names_to = "VARIABLE_LEVEL") %>% subset(value > 0) %>% group_by(WIMD_2014_QUINTILE, VARIABLE_LEVEL) %>% summarise(Total = n())

patient_long_cond_agg_dep <- patients %>% group_by(WIMD_2014_QUINTILE, NUM_CAT) %>% summarise(Total = n())

patient_long_cond_vw_dep <- patients %>% group_by(WIMD_2014_QUINTILE, VW_CAT) %>% summarise(Total = n())

patient_reason_long <- patients[, c(1, 6:46)] %>% pivot_longer(cols = c("RF", "CHF", "CARIT", "VALV", "PCD", "PVD", "HYPUNC", "HYPC", "PARA", "OND", "CPD", "DIABUNC",
                                                                        "DIABC", "HYPOTHY", "LD", "PUD", "LYMPH", "METACANC", "SOLIDTUM", "RHEUMD", "COAG", "OBES", "WLOSS",
                                                                        "FED", "BLANE", "DANE", "ALCOHOL", "DRUG", "PSYCHO", "DEPRE"),
                                                               names_to = "VARIABLE_LEVEL") %>% subset(value > 0)
  
patient_reason_long <- patient_reason_long[, -c(14)] %>% pivot_longer(cols = c("REASON_TRANSPLANT", "REASON_CANCER", "REASON_RESPIRATORY", "REASON_ORGAN_DISEASE", "REASON_RARE_DISEASES", "REASON_IMMUNOSUPPRESSION_THERAPY",
                                                                       "REASON_PREGNANCY", "REASON_RENAL_DIALYSIS", "REASON_OTHER", "REASON_GP_REFERRED", "REASON_NOT_KNOWN"),
                                                              names_to = "Shield_Reason") %>% subset(value > 0) %>% group_by(Shield_Reason, VARIABLE_LEVEL) %>% summarise(Total = n())

patient_reason_long_agg <- patients[, c(1, 6:16, 48)] %>% pivot_longer(cols = c("REASON_TRANSPLANT", "REASON_CANCER", "REASON_RESPIRATORY", "REASON_ORGAN_DISEASE", "REASON_RARE_DISEASES", "REASON_IMMUNOSUPPRESSION_THERAPY",
                                                                       "REASON_PREGNANCY", "REASON_RENAL_DIALYSIS", "REASON_OTHER", "REASON_GP_REFERRED", "REASON_NOT_KNOWN"),
                                                              names_to = "Shield_Reason") %>% subset(value > 0) %>% group_by(Shield_Reason, NUM_CAT) %>% summarise(Total = n())

patient_reason_long_vw <- patients[, c(1, 6:16, 50)] %>% pivot_longer(cols = c("REASON_TRANSPLANT", "REASON_CANCER", "REASON_RESPIRATORY", "REASON_ORGAN_DISEASE", "REASON_RARE_DISEASES", "REASON_IMMUNOSUPPRESSION_THERAPY",
                                                                       "REASON_PREGNANCY", "REASON_RENAL_DIALYSIS", "REASON_OTHER", "REASON_GP_REFERRED", "REASON_NOT_KNOWN"),
                                                              names_to = "Shield_Reason") %>% subset(value > 0) %>% group_by(Shield_Reason, VW_CAT) %>% summarise(Total = n())
```

```{r nulls, echo = F}
nulls <- nulls %>% distinct(ALF_PE, .keep_all = T)

nulls_sex <- nulls %>% group_by(SEX) %>% summarise(Total = n())

nulls_sex_age <- nulls %>% group_by(SEX, Age_Group) %>% summarise(Total = n())

nulls_age <- nulls %>% group_by(Age_Group) %>% summarise(Total = n())

nulls_dep <- nulls %>% group_by(WIMD_2014_QUINTILE) %>% summarise(Total = n())

nulls_reason <- nulls %>% pivot_longer(cols = c("TRANSPLANT", "CANCER", "RESPIRATORY", "ORGAN_DISEASE", "RARE_DISEASES", "IMMUNOSUPPRESSION_THERAPY",
                                                        "PREGNANCY", "RENAL_DIALYSIS", "OTHER", "GP_REFERRED", "NOT_KNOWN"),
                                       names_to = "Shield_Reason") %>% subset(value > 0) %>% group_by(Shield_Reason) %>% summarise(Total = n())
```