---
title: "Mortality statistics for CEV people compared to the general population"
author: "Sebastien Peytrignet"
date: "11/6/2021"
output:
  html_document:
    toc: true
---

## Setup

```{r setup.A, echo=TRUE, message=FALSE}
#Load packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,stringr,ggplot2,easycsv,readxl,
               gmodels,DescTools,data.table,
               tibble,plotly,lubridate,
               here,RColorBrewer,ggthemes,hrbrthemes,
               tidyverse,showtext,tidytext,
               knitr,kableExtra)

#Clean up the global environment
rm(list = ls())

#Set directory where inputs are saved
rawdatadir <- "M:/Analytics/Networked Data Lab/Shielding/Tracking Healthcare Activity and Outcomes/Sep 2020/"

#Git directory
gitdir <- rstudioapi::getSourceEditorContext()$path %>%
  dirname(.) %>%
  dirname(.) %>%
  dirname(.)

#One drive directory
onedrivedir <- "C:/Users/SebastienP/OneDrive - The Health Foundation/Output 3/Charts/"

#Auxiliary function
numbers_only <- function(x) !grepl("\\D", x)
```

## Reading in data and data cleaning

```{r setup.B, echo=TRUE, message=FALSE}
####################################################################
##################### Import NHS Digital data  #####################
####################################################################

nhsdigital.mortality <- fread(paste0(rawdatadir,"Tracking Healthcare Activity and Outcomes for Shielded Patients, England, Open Data.csv"),header=TRUE, sep=",", check.names=T) %>%
  filter(.,Activity_type=="Mortality",Breakdown=="All",Rate!="NULL") %>%
  mutate(.,Rate=as.numeric(Rate)) %>%
  select(.,Population_group,Breakdown,Date,Rate,Numerator,Denominator) %>%
  pivot_wider(
    names_from = Population_group,
    names_sep = ".",
    values_from = c(Rate,Numerator,Denominator)
  ) %>%
  mutate(.,Date=lubridate::dmy(Date)) %>%
  filter(.,Date<="2020-08-30")

nhsdigital.mortality %>%
  filter(.,Date<="2020-07-31") %>%
  head(.,n=10) %>%
  kable(.,format.args = list(big.mark = ",")) %>%
  kable_styling(., full_width = F)
```

## Peak mortality in both groups

```{r peaks, echo=TRUE}
nhsdigital.mortality %>%
  filter(.,Date<="2020-07-31") %>%
  slice_max(Rate.SPL,n=1) %>%
  kable(.,format.args = list(big.mark = ",")) %>%
  kable_styling(., full_width = F)

nhsdigital.mortality %>%
  filter(.,Date<="2020-07-31") %>%
  slice_max(`Rate.General population`,n=1) %>%
  slice_min(.,Date) %>%
  kable(.,format.args = list(big.mark = ",")) %>%
  kable_styling(., full_width = F)
```

## Number dead between March and August 2020

```{r totaldead, echo=TRUE}
nhsdigital.mortality %>%
  pull(.,Numerator.SPL) %>%
  as.numeric() %>%
  sum(.) %>%
  kable(.,format.args = list(big.mark = ",")) %>%
  kable_styling(., full_width = F)
```

## Change in mortality rate between 23/03/2020 and 02/04/2020

```{r change, echo=TRUE}
nhsdigital.mortality %>%
  filter(.,Date %in% as.Date(c("2020-03-23","2020-04-02"))) %>%
  select(.,Date,Rate.SPL,`Rate.General population`) %>%
  pivot_wider(
    names_from = Date,
    names_sep = ".",
    values_from = c(`Rate.SPL`,`Rate.General population`)
  ) %>%
  mutate(.,pct_increase_SPL=(`Rate.SPL.2020-04-02`-`Rate.SPL.2020-03-23`)/`Rate.SPL.2020-03-23`*100,
         pct_increase_gen_pop=(`Rate.General population.2020-04-02`-`Rate.General population.2020-03-23`)/`Rate.General population.2020-03-23`*100) %>%
  kable(.,format.args = list(big.mark = ",")) %>%
  kable_styling(., full_width = F)
```
